name: Code Style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check if source code is formatted
      run: |
        dotnet format src/SMTDafnyCompiler.sln --verify-no-changes